# Generated by Django 4.2.11 on 2024-04-11 18:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0004_alter_genre_id_alter_movie_id_alter_mylist_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={
                "ordering": ("name",),
                "verbose_name": "genre",
                "verbose_name_plural": "genres",
            },
        ),
    ]
